"""Adds a Arch model

Revision ID: 4ace333da7ba
Revises: c7edd97df280
Create Date: 2016-08-24 14:27:05.598814

"""

# revision identifiers, used by Alembic.
revision = '4ace333da7ba'
down_revision = 'c7edd97df280'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archs_name'), 'archs', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archs_name'), table_name='archs')
    op.drop_table('archs')
    ### end Alembic commands ###
