"""Adds a Repo.extra field

Revision ID: 8ddc720fb6d2
Revises: 4ace333da7ba
Create Date: 2016-08-29 09:31:11.953895

"""

# revision identifiers, used by Alembic.
revision = '8ddc720fb6d2'
down_revision = '4ace333da7ba'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('extra', shaman.models.types.JSONType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'extra')
    ### end Alembic commands ###
