"""Add flavor to Repo model

Revision ID: c7edd97df280
Revises: 
Create Date: 2016-08-10 16:00:56.243079

"""

# revision identifiers, used by Alembic.
revision = 'c7edd97df280'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('flavor', sa.String(length=256), nullable=False, server_default='default'))
    op.create_index(op.f('ix_repos_flavor'), 'repos', ['flavor'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repos_flavor'), table_name='repos')
    op.drop_column('repos', 'flavor')
    ### end Alembic commands ###
