"""create the build model

Revision ID: cc3cddf3efb0
Revises: 8ddc720fb6d2
Create Date: 2016-09-22 15:12:42.043626

"""

# revision identifiers, used by Alembic.
revision = 'cc3cddf3efb0'
down_revision = '8ddc720fb6d2'
branch_labels = None
depends_on = None

import shaman
from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('log_url', sa.String(length=256), nullable=True),
    sa.Column('build_id', sa.String(length=64), nullable=True),
    sa.Column('ref', sa.String(length=256), nullable=True),
    sa.Column('sha1', sa.String(length=256), nullable=True),
    sa.Column('flavor', sa.String(length=256), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('extra', shaman.models.types.JSONType(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builds_build_id'), 'builds', ['build_id'], unique=False)
    op.create_index(op.f('ix_builds_completed'), 'builds', ['completed'], unique=False)
    op.create_index(op.f('ix_builds_flavor'), 'builds', ['flavor'], unique=False)
    op.create_index(op.f('ix_builds_modified'), 'builds', ['modified'], unique=False)
    op.create_index(op.f('ix_builds_sha1'), 'builds', ['sha1'], unique=False)
    op.create_index(op.f('ix_builds_started'), 'builds', ['started'], unique=False)
    op.create_index(op.f('ix_builds_status'), 'builds', ['status'], unique=False)
    op.create_index(op.f('ix_builds_ref'), 'builds', ['ref'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_builds_status'), table_name='builds')
    op.drop_index(op.f('ix_builds_started'), table_name='builds')
    op.drop_index(op.f('ix_builds_sha1'), table_name='builds')
    op.drop_index(op.f('ix_builds_modified'), table_name='builds')
    op.drop_index(op.f('ix_builds_flavor'), table_name='builds')
    op.drop_index(op.f('ix_builds_ref'), table_name='builds')
    op.drop_index(op.f('ix_builds_completed'), table_name='builds')
    op.drop_index(op.f('ix_builds_build_id'), table_name='builds')
    op.drop_table('builds')
    ### end Alembic commands ###
