"""adds distro, distro_version and distro_arch to Build

Revision ID: ccb19795cbdc
Revises: cc3cddf3efb0
Create Date: 2016-09-28 14:32:47.578456

"""

# revision identifiers, used by Alembic.
revision = 'ccb19795cbdc'
down_revision = 'cc3cddf3efb0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builds', sa.Column('distro', sa.String(length=256), nullable=True))
    op.add_column('builds', sa.Column('distro_arch', sa.String(length=256), nullable=True))
    op.add_column('builds', sa.Column('distro_version', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_builds_distro'), 'builds', ['distro'], unique=False)
    op.create_index(op.f('ix_builds_distro_arch'), 'builds', ['distro_arch'], unique=False)
    op.create_index(op.f('ix_builds_distro_version'), 'builds', ['distro_version'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_builds_distro_version'), table_name='builds')
    op.drop_index(op.f('ix_builds_distro_arch'), table_name='builds')
    op.drop_index(op.f('ix_builds_distro'), table_name='builds')
    op.drop_column('builds', 'distro_version')
    op.drop_column('builds', 'distro_arch')
    op.drop_column('builds', 'distro')
    ### end Alembic commands ###
