# openshift/deploy/postgres-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: shaman
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: cephfs-rwx   # or omit this line to use the default
  resources:
    requests:
      storage: 10Gi
