---

- name: reload systemd
  become: true
  command: systemctl daemon-reload

- name: restart app
  become: true
  service:
    name: shaman
    state: restarted
    enabled: yes

- name: restart nginx
  become: true
  service:
    name: nginx
    state: restarted
